import re
import json
import pandas as pd


def parse_json(text: str) -> dict:
    """Extract and parse the first JSON object from a string."""
    text = text.strip().replace("```json", "").replace("```", "").strip()
    start = text.index("{")
    end   = text.rindex("}") + 1
    return json.loads(text[start:end])


def format_dataframe_dates(df: pd.DataFrame) -> pd.DataFrame:
    """Format datetime columns to readable format."""
    df = df.copy()
    date_keywords = ['date', 'created_at', 'updated_at', 'review_date', 'recorded_at', 'order_date']

    for col in df.columns:
        col_lower = col.lower()
        if any(keyword in col_lower for keyword in date_keywords):
            try:
                if pd.api.types.is_numeric_dtype(df[col]):
                    df[col] = pd.to_datetime(df[col], unit='ms', errors='coerce')
                else:
                    df[col] = pd.to_datetime(df[col], errors='coerce')
                if pd.api.types.is_datetime64_any_dtype(df[col]):
                    df[col] = df[col].dt.strftime('%Y-%m-%d %H:%M:%S')
            except Exception:
                pass
        elif pd.api.types.is_datetime64_any_dtype(df[col]):
            try:
                df[col] = df[col].dt.strftime('%Y-%m-%d %H:%M:%S')
            except Exception:
                pass

    return df


def fix_sqlite_backticks(sql: str) -> str:
    """
    Fix misplaced backtick quotes generated by LLMs for SQLite column names.

    Two patterns LLMs produce:
      1. `name`) → `name)` (backtick closed before trailing paren in content)
      2. `name)` where content has unbalanced parens → move extra ) outside
         e.g. `CDSCode)` → `CDSCode`)
         e.g. `Enrollment (Ages 5-17))` → `Enrollment (Ages 5-17)`)
    """
    def fix_token(m):
        content = m.group(1)
        open_p  = content.count("(")
        close_p = content.count(")")
        if open_p == close_p:
            return f"`{content}`"
        if close_p > open_p:
            # Move the extra closing parens outside the backtick
            extra = close_p - open_p
            trimmed = content
            suffix = ""
            for _ in range(extra):
                if trimmed.endswith(")"):
                    trimmed = trimmed[:-1]
                    suffix += ")"
            return f"`{trimmed}`{suffix}"
        # open_p > close_p: backtick closed too early before a closing paren
        return f"`{content}`"

    # Handle: `name`) → `name)` first (backtick before trailing paren)
    sql = re.sub(r'`([^`]+)`\)', lambda m: f"`{m.group(1)})`", sql)
    # Now fix unbalanced parens inside backtick tokens
    sql = re.sub(r'`([^`]+)`', fix_token, sql)
    return sql


def format_sql(sql: str) -> str:
    """Format SQL query with line breaks before major keywords."""
    sql = sql.strip()
    keywords = ['SELECT', 'FROM', 'JOIN', 'LEFT JOIN', 'RIGHT JOIN',
                'WHERE', 'GROUP BY', 'HAVING', 'ORDER BY', 'LIMIT']
    for keyword in keywords:
        pattern = re.compile(re.escape(keyword), re.IGNORECASE)
        sql = pattern.sub(f'\n{keyword}', sql)
    lines = [line.strip() for line in sql.split('\n') if line.strip()]
    return '\n'.join(lines)
